### ISSUE TITLE
 replace field injection by constructor injection and make fields private final

### ISSUE THREAD

**Issue by grigoriy-orlov** [pochivalin-alexey/Congrat#8]
https://github.com/gorchok/Congrat/blob/18f17fb7b4bcc8b735fc895bbabfb5eb0b809b88/src/main/java/ru/congrat/services/PersonServiceImpl.java#L17

**Comment by pochivalin-alexey** [comment]
why constructor injection is better ?

**Comment by grigoriy-orlov** [comment]
For example, ctor injection  is better for unit testing. And because of final fields it is thread safe. Read in the internet.
